version: "3.9"
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
      - "5900:5900"
    volumes:
      - ./container/app/src:/container/app/src/
      - ./container/backend/:/container/backend/
      - ./node_moudles:/node_moudles

    stdin_open: true
    tty: true
    depends_on:
      - db
    restart: always
    env_file:
      - ./backend/src/config/.env

  db:
    image: mongo:4.4.6
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_db:
